name: Build APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip git zip unzip openjdk-17-jdk autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev cmake libffi-dev libssl-dev
          pip3 install --upgrade buildozer cython

      - name: Build
        env:
          BUILDOZER_ALLOW_ROOT: 1
        run: |
          # Главная магия: принудительное принятие всех лицензий
          # yes 'y' подает 'y' на каждый запрос подтверждения
          yes | sdkmanager --licenses || true
          
          # Запуск сборки
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: WiFiAtak-APK
          path: bin/*.apk
          
